language: node_js
node_js:
- '0.10'
- '0.12'
before_install:
- npm install -g npm
install:
- npm install
- cd ./example && npm install && cd -
script:
- npm test
- cd example && node ./build.js && cd -
deploy:
  provider: npm
  email: aymeric@beaumet.me
  api_key:
    secure: NsrKXS5r+zjfCq1Mv4kyFUh3rpHIv/JcghTfUdrnII0RzQJbK0lbYcyd0sel3W63hxITSm6rsCHNzMW55+yozFmPwzz2pQEzsvm6/oMo0LrN87O1OuHVciW7C6dqtHwEaY+3fPG5rc2KuZhWIxRS0ZRr1rKFMFkGHw0MJsa/QSg=
  on:
    repo: aymericbeaumet/metalsmith-redirect
    branch: master
    tags: true
